apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-detection-sa
  namespace: fraud-detection
  annotations:
    # Workload Identity — links this K8s ServiceAccount to a GCP ServiceAccount
    # Allows pods to access Secret Manager without storing credentials in the cluster
    iam.gke.io/gcp-service-account: fraud-detection-sa@streaming-fraud-intelligence.iam.gserviceaccount.com